version: "3"
services:
  web:
    build:
      context: .
    env_file: .docker-env
    volumes:
      - .:/grade_app
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    entrypoint: bash -c
    command: |
      "bundle install && \
      bundle exec rails s -b 0.0.0.0 -p 3000"
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
