default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  port: 3306

development:
  <<: *default
  username: root
  host: db
  database: grade_share_development
  socket: /tmp/mysql.sock

test:
  <<: *default
  username: root
  host: <%= ENV['DB_HOST']%>

production:
  <<: *default
  database: grade_app_production
  username: grade_app
  password: <%= ENV['GRADE_APP_DATABASE_PASSWORD'] %>
